// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/admin/(panel)/clientes/[slug]/landing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/clientes/[slug]/landing">> = Specific
  const handler = {} as typeof import("../../src/app/admin/(panel)/clientes/[slug]/landing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/(panel)/clientes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/clientes">> = Specific
  const handler = {} as typeof import("../../src/app/admin/(panel)/clientes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/(panel)/configuracion/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/configuracion">> = Specific
  const handler = {} as typeof import("../../src/app/admin/(panel)/configuracion/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/(panel)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/(panel)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/(panel)/planes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/planes">> = Specific
  const handler = {} as typeof import("../../src/app/admin/(panel)/planes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/login">> = Specific
  const handler = {} as typeof import("../../src/app/admin/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/ayuda/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ayuda">> = Specific
  const handler = {} as typeof import("../../src/app/ayuda/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/empezar/wizard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/empezar/wizard">> = Specific
  const handler = {} as typeof import("../../src/app/empezar/wizard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/expired/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/expired">> = Specific
  const handler = {} as typeof import("../../src/app/expired/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/forgot-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forgot-password">> = Specific
  const handler = {} as typeof import("../../src/app/forgot-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/panel/calendario/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/panel/calendario">> = Specific
  const handler = {} as typeof import("../../src/app/panel/calendario/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/panel/campanas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/panel/campanas">> = Specific
  const handler = {} as typeof import("../../src/app/panel/campanas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/panel/clientes/[email]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/panel/clientes/[email]">> = Specific
  const handler = {} as typeof import("../../src/app/panel/clientes/[email]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/panel/clientes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/panel/clientes">> = Specific
  const handler = {} as typeof import("../../src/app/panel/clientes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/panel/configuracion/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/panel/configuracion">> = Specific
  const handler = {} as typeof import("../../src/app/panel/configuracion/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/panel/equipo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/panel/equipo">> = Specific
  const handler = {} as typeof import("../../src/app/panel/equipo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/panel/landing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/panel/landing">> = Specific
  const handler = {} as typeof import("../../src/app/panel/landing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/panel/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/panel">> = Specific
  const handler = {} as typeof import("../../src/app/panel/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/panel/productos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/panel/productos">> = Specific
  const handler = {} as typeof import("../../src/app/panel/productos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/panel/reservas/nueva/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/panel/reservas/nueva">> = Specific
  const handler = {} as typeof import("../../src/app/panel/reservas/nueva/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/panel/reservas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/panel/reservas">> = Specific
  const handler = {} as typeof import("../../src/app/panel/reservas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/panel/servicios/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/panel/servicios">> = Specific
  const handler = {} as typeof import("../../src/app/panel/servicios/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/registro/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/registro">> = Specific
  const handler = {} as typeof import("../../src/app/registro/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reserva/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reserva">> = Specific
  const handler = {} as typeof import("../../src/app/reserva/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reset-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reset-password">> = Specific
  const handler = {} as typeof import("../../src/app/reset-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/suspended/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/suspended">> = Specific
  const handler = {} as typeof import("../../src/app/suspended/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/migrate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/migrate">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/migrate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/google/auth/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/google/auth">> = Specific
  const handler = {} as typeof import("../../src/app/api/google/auth/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/google/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/google/callback">> = Specific
  const handler = {} as typeof import("../../src/app/api/google/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/google/disconnect/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/google/disconnect">> = Specific
  const handler = {} as typeof import("../../src/app/api/google/disconnect/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/google/webhook/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/google/webhook">> = Specific
  const handler = {} as typeof import("../../src/app/api/google/webhook/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/imp/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/imp">> = Specific
  const handler = {} as typeof import("../../src/app/api/imp/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/landing-config/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/landing-config">> = Specific
  const handler = {} as typeof import("../../src/app/api/landing-config/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tenants/create/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tenants/create">> = Specific
  const handler = {} as typeof import("../../src/app/api/tenants/create/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/upload">> = Specific
  const handler = {} as typeof import("../../src/app/api/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/auth/callback">> = Specific
  const handler = {} as typeof import("../../src/app/auth/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/admin/(panel)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/(panel)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/empezar/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/empezar">> = Specific
  const handler = {} as typeof import("../../src/app/empezar/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/panel/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/panel">> = Specific
  const handler = {} as typeof import("../../src/app/panel/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reserva/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/reserva">> = Specific
  const handler = {} as typeof import("../../src/app/reserva/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
