# BEGIN GDO_CANNIB_REDIRECTS
# Generated: 2026-04-23T20:38:53.933Z
# Add INSIDE <VirtualHost> or at top of .htaccess (before WordPress block)
<IfModule mod_alias.c>
  Redirect 301 /belleza-bienestar/extension-pestanas-salon-rd/ https://xn--gestindo-z3a.com/belleza-bienestar/lash-lifting-salon-rd/
  Redirect 301 /finanzas-legalidad/propina-legal-10-rd/ https://xn--gestindo-z3a.com/gastronomia/propina-legal-restaurantes-rd/
</IfModule>
# END GDO_CANNIB_REDIRECTS